# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
delay = 1000 # ms
stop_signal = "SIGTERM"
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = "/app/tmp/main"

[log]
time = true
level = "debug"

[misc]
clean_on_exit = true
